### ISSUE TITLE
NATS_JETSTREAM_OPTIONS dependency error

### ISSUE THREAD

**Issue by raarts** [Redningsselskapet/nestjs-nats-jetstream-transport#1]
Hi, 

I followed the example in the readme to the letter (which by the way contains errors, they import using the name `nats-jetstream-transport`, without the `nestjs` prefix), but I stumble upon the error above.

I'm not a seasoned Nestjs developer yet. Normally when I get errors like this, I just add the relevant provider to the `providers:`  key, but this is a constant, and I don't know where to add it.

```
Error: Nest can't resolve dependencies of the NatsJetStreamClientProxy (?). Please make sure that the argument NATS_JETSTREAM_OPTIONS at index [0] is available in the CommandModule context.

Potential solutions:
- If NATS_JETSTREAM_OPTIONS is a provider, is it part of the current CommandModule?
- If NATS_JETSTREAM_OPTIONS is exported from a separate @Module, is that module imported within CommandModule?
  @Module({
    imports: [ /* the Module containing NATS_JETSTREAM_OPTIONS */ ]
  })
```

**Comment by kenguru33** [comment]
This is an old abounded repository in the early development phase. Has just forgotten to delete it. Sorry about that.

You will find the correct repo here: https://github.com/Redningsselskapet/nestjs-plugins.

But I guess you already have found it as you have reported issues there as well. ;)
